name: Build
on: workflow_dispatch
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    name: build
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Pip install
        run: pip install -r requirements.txt
      - name: Actually build
        run: python setup.py build
      - name: Package Linux
        run: |
          cd build
          tar cvfz systems_design.tar.gz *linux*
        if: matrix.os == 'ubuntu-latest'
      - name: Package Windows
        run: |
          cd build
          Compress-Archive -Path .\exe.windows-3.11 -DestinationPath .\systems_design.zip
        if: matrix.os == 'windows-latest'
    
